import { useFormContext } from "react-hook-form"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Card, CardContent } from "@/components/ui/card"
import { Globe, Server } from "lucide-react"

export default function StepThree() {
  const { register, watch, setValue } = useFormContext()
  const enableOnboarding = watch("enableOnboarding")
  const autoGenerateDashboard = watch("autoGenerateDashboard")

  return (
    <div className="space-y-8">
      <div>
        <h2 className="text-xl font-semibold text-gray-900 mb-6">Company Configuration</h2>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-2">
            <Label htmlFor="subdomain">Subdomain *</Label>
            <div className="flex">
              <Input
                id="subdomain"
                placeholder="Enter company name"
                {...register("subdomain", { required: true })}
                className="rounded-r-none"
              />
              <div className="bg-gray-100 border border-l-0 px-3 py-2 rounded-r text-sm text-gray-600">
                .thetaanalyzer.com
              </div>
            </div>
          </div>

          <div className="space-y-2">
            <Label>Region/Server Location *</Label>
            <Select value={watch("region")} onValueChange={(value) => setValue("region", value)}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="US-East">US-East</SelectItem>
                <SelectItem value="US-West">US-West</SelectItem>
                <SelectItem value="EU-West">EU-West</SelectItem>
                <SelectItem value="Asia-Pacific">Asia-Pacific</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <Label>Time zone</Label>
            <Select value={watch("timezone")} onValueChange={(value) => setValue("timezone", value)}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="[UTC-05:00] Eastern Time (US & Canada)">
                  [UTC-05:00] Eastern Time (US & Canada)
                </SelectItem>
                <SelectItem value="[UTC-08:00] Pacific Time (US & Canada)">
                  [UTC-08:00] Pacific Time (US & Canada)
                </SelectItem>
                <SelectItem value="[UTC+00:00] Greenwich Mean Time">[UTC+00:00] Greenwich Mean Time</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <Label>Default Language</Label>
            <Select value={watch("defaultLanguage")} onValueChange={(value) => setValue("defaultLanguage", value)}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="English">English</SelectItem>
                <SelectItem value="Spanish">Spanish</SelectItem>
                <SelectItem value="French">French</SelectItem>
                <SelectItem value="German">German</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
      </div>

      <div>
        <h3 className="text-lg font-medium text-blue-600 mb-4">System Setup</h3>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-4">
            <div className="flex items-center space-x-2">
              <Switch
                id="enableOnboarding"
                checked={enableOnboarding}
                onCheckedChange={(checked) => setValue("enableOnboarding", checked)}
              />
              <Label htmlFor="enableOnboarding">Enable Onboarding Guide</Label>
            </div>
            <p className="text-sm text-gray-600">Client will see onboarding steps and feature checklists.</p>
          </div>

          <div className="space-y-4">
            <div className="flex items-center space-x-2">
              <Switch
                id="autoGenerateDashboard"
                checked={autoGenerateDashboard}
                onCheckedChange={(checked) => setValue("autoGenerateDashboard", checked)}
              />
              <Label htmlFor="autoGenerateDashboard">Auto-Generate Welcome Dashboard</Label>
            </div>
            <p className="text-sm text-gray-600">Create a default dashboard with 3 KPIs and 1 chart.</p>
          </div>
        </div>

        <div className="mt-6">
          <Label>Assign Industry Template *</Label>
          <Select value={watch("industryTemplate")} onValueChange={(value) => setValue("industryTemplate", value)}>
            <SelectTrigger className="mt-2">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="Real Estate">Real Estate</SelectItem>
              <SelectItem value="Healthcare">Healthcare</SelectItem>
              <SelectItem value="Finance">Finance</SelectItem>
              <SelectItem value="Retail">Retail</SelectItem>
              <SelectItem value="Manufacturing">Manufacturing</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </div>

      <div>
        <h3 className="text-lg font-medium text-blue-600 mb-4">Instance Preview</h3>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <Card>
            <CardContent className="p-4">
              <div className="flex items-center space-x-3">
                <Globe className="h-8 w-8 text-blue-600" />
                <div>
                  <div className="font-medium">Client URL</div>
                  <div className="text-sm text-gray-600">{watch("subdomain") || "acme"}.thetaanalyzer.com</div>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-4">
              <div className="flex items-center space-x-3">
                <Server className="h-8 w-8 text-blue-600" />
                <div>
                  <div className="font-medium">Server Location</div>
                  <div className="text-sm text-gray-600">{watch("region")} (Virginia)</div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
