import StepOne from "@/components/admin/addClientSteps/stepOne"
import StepTwo from "@/components/admin/addClientSteps/stepTwo"
import StepThree from "@/components/admin/addClientSteps/stepThree"
import StepFour from "@/components/admin/addClientSteps/stepFour"
import StepFive from "@/components/admin/addClientSteps/stepFive"
import { useState } from "react"
import { useForm, FormProvider, SubmitHandler } from "react-hook-form"
import { Card, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Home, Users, Plus } from "lucide-react"

const steps = [
  { id: 1, title: "Create Account", icon: "1" },
  { id: 2, title: "Branding & Layout", icon: "2" },
  { id: 3, title: "Add Instance", icon: "3" },
  { id: 4, title: "Test All Library", icon: "4" },
  { id: 5, title: "Storage & Subscription", icon: "5" },
]


interface FormValues {
  // Step 1 - Create Account
  clientName: string
  email: string
  contactPersonName: string
  phoneNumber: string
  isReferred: boolean
  referrerName: string
  referrerEmail: string
  referrerPhone: string
  howDidHear: string

  // Step 2 - Branding & Layout
  clientLogo: File | null
  favicon: File | null
  primaryColor: string
  secondaryColor: string
  showFooter: boolean
  customFooterText: string
  supportContactLink: string

  // Step 3 - Add Instance
  subdomain: string
  region: string
  timezone: string
  defaultLanguage: string
  enableOnboarding: boolean
  autoGenerateDashboard: boolean
  industryTemplate: string

  // Step 4 - Test All Library
  selectedTeamMember: string
  notifyDevTeam: boolean

  // Step 5 - Storage & Subscription
  storageQuota: string
  archiveAfter: string
  enableUsageWarning: boolean
  billingCycle: string
  subscriptionPlan: string
  startBillingDate: string
  trialPeriod: string
  paymentMethod: string
  discountCode: string
  internalNotes: boolean
  adminNote: string
}

export default function MultiLevelForm() {
  const [currentStep, setCurrentStep] = useState(1)
  const [allFormData, setAllFormData] = useState({})

  const methods = useForm<FormValues>({
    defaultValues: {
      // Step 1 - Create Account
      clientName: "",
      email: "",
      contactPersonName: "",
      phoneNumber: "",
      isReferred: false,
      referrerName: "",
      referrerEmail: "",
      referrerPhone: "",
      howDidHear: "",

      // Step 2 - Branding & Layout
      clientLogo: null,
      favicon: null,
      primaryColor: "#7F50D9",
      secondaryColor: "#6366F1",
      showFooter: true,
      customFooterText: "© 2023 Client Company. All rights reserved",
      supportContactLink: "Mail to: support@thetaanalyzer.com",

      // Step 3 - Add Instance
      subdomain: "",
      region: "US-East",
      timezone: "[UTC-05:00] Eastern Time (US & Canada)",
      defaultLanguage: "English",
      enableOnboarding: true,
      autoGenerateDashboard: true,
      industryTemplate: "Real Estate",

      // Step 4 - Test All Library
      selectedTeamMember: "",
      notifyDevTeam: false,

      // Step 5 - Storage & Subscription
      storageQuota: "10",
      archiveAfter: "90",
      enableUsageWarning: true,
      billingCycle: "Monthly",
      subscriptionPlan: "",
      startBillingDate: "",
      trialPeriod: "15",
      paymentMethod: "Stripe",
      discountCode: "",
      internalNotes: true,
      adminNote: "",
    },
  })

  const nextStep = () => {
    if (currentStep < 5) {
      // Get current form data and merge with existing data
      const currentData = methods.getValues()
      setAllFormData((prev) => ({ ...prev, ...currentData }))
      setCurrentStep(currentStep + 1)
    }
  }

  const prevStep = () => {
    if (currentStep > 1) {
      setCurrentStep(currentStep - 1)
    }
  }

  const handleSubmit:SubmitHandler<FormValues> = (data) => {
    const finalData = { ...allFormData, ...data }
    setAllFormData(finalData)
    console.log("Complete Form Data:", finalData)
    alert("Form submitted successfully! Check console for all data.")
  }

  const renderStep = () => {
    switch (currentStep) {
      case 1:
        return <StepOne />
      case 2:
        return <StepTwo />
      case 3:
        return <StepThree />
      case 4:
        return <StepFour />
      case 5:
        return <StepFive />
      default:
        return <StepOne />
    }
  }

  console.log(JSON.stringify({ ...allFormData, ...methods.watch() }, null, 2))

  return (
    <div className="mt-10 p-4">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center space-x-2">
            <Home className="h-5 w-5 text-gray-500" />
            <span className="text-gray-500">Home</span>
            <span className="text-gray-500">/</span>
            <Users className="h-5 w-5 text-gray-500" />
            <span className="text-gray-500">Clients</span>
            <span className="text-gray-500">/</span>
            <Plus className="h-5 w-5 text-blue-600" />
            <span className="text-blue-600 font-medium">Add Client</span>
          </div>
          <Button variant="outline">Save Draft</Button>
        </div>

        {/* Title */}
        <div className="mb-8">
          <h1 className="text-2xl font-bold text-gray-900 mb-2">Create New Client</h1>
          <p className="text-gray-600">Add new clients to your Theta analyzers</p>
        </div>

        {/* Progress Steps */}
        <div className="mb-8">
          <div className="flex items-center justify-between mb-4 relative">
            {/* Connecting line background */}
            <div className="absolute top-5 left-5 right-5 h-0.5 bg-gray-200 -z-10"></div>

            {steps.map((step, index) => (
              <div key={step.id} className="flex flex-col items-center relative">
                {/* Connecting line for completed steps */}
                {index > 0 && currentStep > step.id && (
                  <div className="absolute top-5 -left-16 w-32 h-0.5 bg-blue-600 -z-10"></div>
                )}

                <div
                  className={`w-10 h-10 rounded-full flex items-center justify-center text-sm font-medium relative z-10 ${
                    currentStep === step.id
                      ? "bg-blue-600 text-white border-4 border-blue-100"
                      : currentStep > step.id
                        ? "bg-blue-600 text-white"
                        : "bg-white text-gray-600 border-2 border-gray-200"
                  }`}
                >
                  {currentStep > step.id ? (
                    <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                      <path
                        fillRule="evenodd"
                        d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                        clipRule="evenodd"
                      />
                    </svg>
                  ) : (
                    step.icon
                  )}
                </div>
                <span
                  className={`text-xs mt-2 text-center max-w-20 leading-tight ${
                    currentStep === step.id ? "text-blue-600 font-medium" : "text-gray-500"
                  }`}
                >
                  {step.title}
                </span>
              </div>
            ))}
          </div>

          {/* Progress bar */}
          <div className="w-full bg-gray-200 rounded-full h-1">
            <div
              className="bg-blue-600 h-1 rounded-full transition-all duration-300 ease-in-out"
              style={{ width: `${(currentStep / 5) * 100}%` }}
            ></div>
          </div>
        </div>

        {/* Form Content */}
        <FormProvider {...methods}>
          <form onSubmit={methods.handleSubmit(handleSubmit)}>
            <Card className="border border-gray-200 shadow-md">
              <CardContent className="p-6">{renderStep()}</CardContent>
            </Card>

            {/* Navigation Buttons */}
            <div className="flex justify-between mt-6 cursor-pointer">
              <Button type="button" variant="outline" onClick={prevStep} disabled={currentStep === 1}>
                {currentStep === 1 ? "Cancel" : "Previous"}
              </Button>

              {currentStep === 5 ? (
                <Button type="submit" className="bg-blue-600 hover:bg-blue-700 cursor-pointer">
                  Submit
                </Button>
              ) : (
                <Button type="button" onClick={nextStep} className="bg-blue-600 text-white cursor-pointer hover:bg-blue-700">
                  Next
                </Button>
              )}
            </div>
          </form>
        </FormProvider>

        {/* Debug: Show current form data */}
        <div className="mt-8 p-4 bg-gray-100 rounded-lg">
          <h3 className="font-medium mb-2">Current Form Data (Debug):</h3>
          <pre className="text-xs overflow-auto">{JSON.stringify({ ...allFormData, ...methods.watch() }, null, 2)}</pre>
        </div>
      </div>
    </div>
  )
}
