export const chartTypes: { [key: string]: string } = {
  BAR: "barChart",
  LINE: "multiAxisChart",
  HORIZONTAL_BAR: "horizontalBarChart",
  STACK_BAR_HORIZONTAL: "stackedBarChart",
  COLUMN: "columnChart",
  PIE: "pi",
  DOUGHNUT: "doughnutChart",
  RADAR: "radarChart",
  HEATMAP: "heatMapChart",
  AREA: "areaChart",
  MIXED: "multiAxisChart",
  PARETO: "paretoChart",
  HISTOGRAM: "histogramChart",
  SCATTER: "scatterChart",
  GAUGE: "solidGaugeChart",
  FUNNEL: "funnelChart",
  WATERFALL: "waterfallChart",
  CANDLESTICK: "candlestickChart",
  SPLINE: "splineChart",
  SPARKLINE: "sparklineChart",
};
